// Free-at-scale carrier lookup.
//
// Google's libphonenumber project ships Apache-2.0 carrier prefix data — the
// same table their PhoneNumberToCarrierMapper uses in Java. We bundle a copy
// of that data (generated by scripts/build-carrier-data.mjs) and look up
// the carrier via longest-prefix match on the digits after the "+".
//
// This is what BeenVerified, TruthFinder and every "free" carrier-lookup
// site actually do behind the scenes: prefix data is free and public, HLR
// lookups are not. It won't reflect number-porting (once someone moves from
// AT&T to T-Mobile, this table still says AT&T), but it's the standard
// tradeoff for a free-at-scale solution.
//
// For countries where Google has no carrier file (Mexico, Argentina, some
// smaller markets) we fall back to a per-country major-network hint.

import carrierData from "./carrier-data.json";

const CARRIER_TABLE = carrierData as Record<string, string>;

// Longest carrier prefix in the table. Cached so the lookup loop doesn't
// have to compute it every call.
let MAX_PREFIX_LEN = 0;
for (const p of Object.keys(CARRIER_TABLE)) {
  if (p.length > MAX_PREFIX_LEN) MAX_PREFIX_LEN = p.length;
}

export type CarrierResult = {
  carrier?: string;
  source: "libphonenumber" | "country-hint" | "unknown";
};

const COUNTRY_CARRIER_HINT: Record<string, string> = {
  MX: "Telcel / AT&T México / Movistar (major Mexican network)",
  AR: "Personal / Movistar / Claro (major Argentine network)",
  BE: "Proximus / Orange BE / Base (major Belgian network)",
  NG: "MTN / Airtel / Glo / 9mobile (major Nigerian network)",
  KE: "Safaricom / Airtel Kenya / Telkom Kenya (major Kenyan network)",
};

/**
 * Look up a carrier for the given E.164 number by longest-prefix match against
 * Google's libphonenumber carrier database. Runs entirely in-process; no
 * network calls, no keys, no rate limits.
 */
export function lookupCarrier(
  e164: string,
  countryCode?: string,
): CarrierResult {
  const digits = e164.replace(/^\+/, "").replace(/\D/g, "");
  if (!digits) return { source: "unknown" };

  // Try prefixes from longest to shortest until one matches.
  const maxLen = Math.min(MAX_PREFIX_LEN, digits.length);
  for (let len = maxLen; len > 0; len--) {
    const prefix = digits.slice(0, len);
    const hit = CARRIER_TABLE[prefix];
    if (hit) return { carrier: hit, source: "libphonenumber" };
  }

  if (countryCode && COUNTRY_CARRIER_HINT[countryCode]) {
    return { carrier: COUNTRY_CARRIER_HINT[countryCode], source: "country-hint" };
  }

  return { source: "unknown" };
}
